### ISSUE TITLE
Introducing interactive questions for YouTube videos in Google Classroom

### ISSUE THREAD

**Issue by jkaufman-mitre** [cisagov/ScubaGoggles#110]
Educators can now turn any YouTube video into an interactive lesson by adding questions for their students to answer throughout the video. The interactive questions feature turns a passive watching experience into an engaging one, and improves students’ understanding of a subject by providing them with the space to make mistakes, review incorrect answers and assess correct answers at their own pace. 

Publish Date: Tuesday, December 12, 2023
[Update Blog Link](https://workspaceupdates.googleblog.com/2023/12/interactive-questions-for-youtube-videos-google-classroom.html)

**Comment by jkaufman-mitre** [comment]
I believe there is no security implications with this feature. @tmcomeau and @prodjom Can you review to confirm.

**Comment by tmcomeau** [comment]
Concur that there are no security-relevant configuration items for this which could be added to the Classroom SCB. It is more of a content management issue for GWS admins and their organizations to determine which questions should be added. 

However, note that this feature is predicated upon the YouTube service being enabled at the tenant-level within the GWS Admin Console. Whether the YouTube service is enabled for a given organization is a discrete configuration item. While this configuration setting does not fall under any of the existing SCBs for specific apps, it is a good topic to consider for the forthcoming hardening guide which will cover tenant-wide security considerations.

**Comment by jkaufman-mitre** [comment]
This update will be deferred to the hardening guide.
