### ISSUE TITLE
Feedback: No GUI/Front End Availability Solution

### ISSUE THREAD

**Issue by LaurenBassett** [cisagov/ScubaGoggles#124]
# 💡 Summary #

What is the work, as a high-level summary?

We received feedback that we need to include a note in our ReadME that ScubaGoggles is unavailable for users without access to a web browser/the front-end GUI. 

We can update the ReadME, or, I had an idea for a terminal output of the baselines that could be used when the front-end output is not available. 

## Motivation and context ##

Why does this work belong in this project?
This was motivated by the feedback of the code being unusable by those without a front-end available.
This would be useful because...
It could give an abridged version of the baseline outputs for users to run quickly and easily. 

## Implementation notes ##

Please provide details for implementation, such as:

Add a new command option to the python command 
`--nogui`

Using python library 'Rich', create table in terminal with results: 

<img width="1144" alt="Screenshot 2023-12-28 at 3 00 27 PM" src="https://github.com/cisagov/ScubaGoggles/assets/32313952/6c8527e9-17d7-4dce-855d-5c9750aa0999">

I have only run and tested this locally on my Mac. Not sure how this would change for a Windows Machine. 

## Acceptance criteria ##

How do we know when this work is done?
Either a message is added to the ReadMe indicating the output requires a browser to be read, OR, we implement a way to see the output in the terminal.

- [ ] Criterion

**Comment by snarve** [comment]
@LaurenBassett in PR #131 I only see the updated readme, is the code change to view the report in the terminal pushed in the same PR? sorry if I missed it.
