### ISSUE TITLE
Drive Docs 6.1 Confusing

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGoggles#142]
The GWS.DRIVEDOCS.6.1v0.1 policy currently reads as: "Agencies SHOULD either disable Google Drive for Desktop or only allow Google Drive for Desktop on authorized devices."

The rationale reads as: "Saving directly to the cloud reduces the risk of potentially losing data, which is beneficial when dealing with sensitive information and when trying to retain certain files."

These two sections seem to conflict with each other. Enabling Google Drive for Desktop makes it _easier_ to have cloud-only file storage. So the policy seems to be _against_ cloud-only while the rationale is _pro_ cloud-only.

I'd recommend the following changes:
1. Change the policy wording to clarify the true purpose. My recommendation: "Google Drive SHOULD only be enabled for authorized devices." Reasoning: the simplified logic makes it easier to understand the true purpose of the policy. It's not saying that you can't use Drive for Desktop, only that users shouldn't be able to connect their agency Google Drive to something like their personal computer. If an agency wants to disable Drive for Desktop entirely, that still meets the requirements of the policy; there are just no approved computers in that case.
2. Change the rationale so that the true security concerns are highlighted. My recommendation: "Some users may attempt to use Drive for Desktop to connect unapproved devices (e.g., a personal computer), to the agency's Google Drive. Even if done without malicious intent, this represents a security risk as the agency has no ability audit or protect such computers."

**Comment by jkaufman-mitre** [comment]
@adhilto I will discuss with the team and make any necessary changes to the baseline. @prodjom

**Comment by jkaufman-mitre** [comment]
Will make the recommended changes. In addition, will add as a note "If not making it so authorized devices can use this feature, then it shall be disabled." @adhilto

**Comment by jkaufman-mitre** [comment]
After discussing, we will go ahead and re-word the policy in order to make the policy statement clearer. The new policy statement will be "Google Drive SHOULD only be enabled for authorized devices".

**Comment by jkaufman-mitre** [comment]
Changes will be made after the 0.3 release.

**Comment by jkaufman-mitre** [comment]
PR has been created for this update. Please refer to PR 311. Moving to in review.
