### ISSUE TITLE
Gmail Clarify Bypassing Spam Filters

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGoggles#149]
(Using the numbers of the gmail-changes-1 branch)

GWS.GMAIL.14.1v0.1 instructs users to not use an email allowlist, referring to this feature here:
![image](https://github.com/cisagov/ScubaGoggles/assets/106177711/19fd42d0-a6de-4960-a415-e65d1996a548)

However, there is another way to create an allowlist that the baseline does not address:
![image](https://github.com/cisagov/ScubaGoggles/assets/106177711/8e27e27e-f7dc-4bff-8e91-7d05baab6dd4)

What was previously [GWS.GMAIL.18](https://github.com/cisagov/ScubaGoggles/blob/main/baselines/Gmail%20Minimum%20Viable%20Secure%20Configuration%20Baseline%20v0.1.md#18-approved-senders-list) touched on some of these settings, but this group is being deleted. I agree with the deletion of this group--the guidance there was confusing and contradictory--but I would recommend adding a new control group that rules out the various ways users could bypass spam protections.

Proposed group name: "Spam Filtering"

Policies:
1. "Domains SHALL NOT be added to lists that bypass spam filters." With a note: "Note: Allowed senders MAY be added."
2. "Domains SHALL NOT be added to lists that bypass spam filters and hide warnings."
3. "Bypass spam filters and hide warnings for all messages from internal and external senders SHALL NOT be enabled."

**Comment by jkaufman-mitre** [comment]
@adhilto Will discuss this with the team to determine which changes should be made. @prodjom

**Comment by jkaufman-mitre** [comment]
PR has been created. TTP Mappings still need to be done and drift rules need to be created.

**Comment by jkaufman-mitre** [comment]
Drift Rules have been completed. Now only waiting on TTP mappings.

**Comment by jkaufman-mitre** [comment]
Followed-up on the status of the TTP mappings.
