### ISSUE TITLE
Compliance reports per OU

### ISSUE THREAD

**Issue by ebarti** [cisagov/ScubaGoggles#153]
# 💡 Summary #

Currently, the compliance cheks are done at the root OU level. Children OUs can override certain root OU settings, so it would be great to be able to have the compliance report per OU

## Motivation and context ##

Verifying compliance against the root OU is not sufficient to ensure GWS is secure.

## Implementation notes ##

Ideally, and by default, compliance reports would be generated for the multiple OUs (including root) present in GWS. 

When filtering events, if a children OU has no event supporting a given control, then the root OU level control is assumed to be enforced. Conversely, if an event for a given control is detected for a given OU, then the control for that specific OU is updated.

## Acceptance criteria ##

TBD

**Comment by adhilto** [comment]
Thanks for opening this issue.

ScubaGoggles does actually check settings at each OU, though the output for all OUs are listed together in the same report.

See below for an example of what this looks like:
![image](https://github.com/cisagov/ScubaGoggles/assets/106177711/5f1eb5f5-913a-4e3d-b6a9-348771bfdab2)

That said, as some settings are set per-OU and some are just set at the org-level, it's possible that there are some settings that we misclassified as an org-level control when we should be checking at the OU level. If you find a specific example where ScubaGoggles isn't checking something at the OU-level where it should, please let us know.

**Comment by ebarti** [comment]
> Thanks for opening this issue.
> 
> ScubaGoggles does actually check settings at each OU, though the output for all OUs are listed together in the same report.
> 
> See below for an example of what this looks like: ![image](https://private-user-images.githubusercontent.com/106177711/298742723-5f1eb5f5-913a-4e3d-b6a9-348771bfdab2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTM5NDAsIm5iZiI6MTcwNTk5MzY0MCwicGF0aCI6Ii8xMDYxNzc3MTEvMjk4NzQyNzIzLTVmMWViNWY1LTkxM2EtNGUzZC1iNmE5LTM0ODc3MWJmZGFiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwNzA3MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTVlYWI4ZmYwNzdjODI2NDIzYjUyYWM0ZDIzMDhkY2Q0ZmNkYWRhMzJkYmRjNjE4NjZmODU2ZmQzM2Q0MzE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.siHROH4Dq7l903K1AYaUXU0cNgaK8QvJRfoBOHQeNBw)
> 
> That said, as some settings are set per-OU and some are just set at the org-level, it's possible that there are some settings that we misclassified as an org-level control when we should be checking at the OU level. If you find a specific example where ScubaGoggles isn't checking something at the OU-level where it should, please let us know.

Thank you for the prompt response @adhilto. I will open individual issues for each setting evaluation that (I think) is wrong if that is OK.

**Comment by adhilto** [comment]
I'm closing this issue for now, but feel free to open new issues for any setting checks you think are wrong.
