### ISSUE TITLE
Gmail SPF Revision

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGoggles#181]
## Delete GWS.GMAIL.3.1v0.1
Reasoning:
- Not a configuration item (more of a prerequisite)
- There was some confusion about what to do with the list once you have it.
- Also some confusion about IP vs domains (e.g., `include:_spf.google.com`).

## Revise GWS.GMAIL.3.2v0.1
Change to “An SPF policy SHALL be published for each domain that fails all non-approved senders.”
Reasoning:
- "only these" is ambiguous
- Explicitly spell out that non-approved senders should fail

**Comment by jkaufman-mitre** [comment]
Placed on hold until after a discussion about this update.

**Comment by jkaufman-mitre** [comment]
After discussing further, determined that these changes will be made.
