### ISSUE TITLE
Bug with Summary Test Counts

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGoggles#184]
# 🐛 Summary #
The values listed on the summary page for the common controls report are higher than they should be.

## To reproduce ##
Run scubagoggles against common controls. Count the results, they are higher than they should be.

## Expected behavior ##
See screenshot below.

## Any helpful log output or screenshots ##
![image](https://github.com/cisagov/ScubaGoggles/assets/106177711/574613da-88e1-4476-88d0-11a4e5b85ed4)

Correct counts should be: 2 and 31
(so many manual checks are needed because this is a brand new tenant so there are barely any log events, that's not the bug)

I suspect that what's happening is the "Rules" tests are being added in here as well, but haven't fully verified that yet.

**Comment by adhilto** [comment]
A related issue: for rules with no events found, the warning icon is not displayed. Haven't tested, but I suspect the fix will be as simple as changing `'Rule Description': test['ReportDetails']})` to `'Rule Description': result})`

**Comment by LaurenBassett** [comment]
Looking into this more this afternoon. I agree with you that rules are being passed in twice. I think at some point we had rules within common controls which is why things are happening the way they are. I think the culprit starts at line 270 in the reporter, but I could be wrong.
