### ISSUE TITLE
Chat - handle group override policy

### ISSUE THREAD

**Issue by snarve** [cisagov/ScubaGoggles#192]
# 🐛 Summary #

Add support for group override polices for Chat baselines

Related Epic: https://github.com/cisagov/ScubaGoggles/issues/190

**Comment by adhilto** [comment]
I just reviewed the admin center, chat settings cannot actually be controlled at the group level.

Note the difference between Calendar (which can be controlled at the group level)
![image](https://github.com/cisagov/ScubaGoggles/assets/106177711/65cb7b1e-2d80-4a32-add9-e3f6adeeef59)

and Chat (which apparently cannot)
![image](https://github.com/cisagov/ScubaGoggles/assets/106177711/b407edbc-86af-4b95-9b2a-04a3fdb66e36)
