### ISSUE TITLE
Sites - handle group override policy

### ISSUE THREAD

**Issue by snarve** [cisagov/ScubaGoggles#193]
# 🐛 Summary #

Add support for group override polices for Sites baselines

Related Epic: https://github.com/cisagov/ScubaGoggles/issues/190

**Comment by adhilto** [comment]
Just verified, this can be set at the group level for Sites.

**Comment by snarve** [comment]
Based on discussion with Alden, this requires specific code changes, hence moving this back to open, and will be handled once the other baselines are covered.
