### ISSUE TITLE
Detailed Report Message for GWS.CHAT.7.1 and GWS.CHAT.7.2

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGoggles#210]
# 💡 Summary #
Refactor GWS.CHAT.7.1 and 7.2 to include a detailed report message in the report.

## Motivation and context ##
- Chat has already been refactored to include detailed report messages
- But new controls are being added to Chat: https://github.com/cisagov/ScubaGoggles/pull/187
- While the ideal would be to add the new code with detailed report messaging, GWS.CHAT.7.1 involves multiple settings simultaneously (4 to be precise), something the existing utils code is not able to handle yet.
- An update to allow the report details to detail multiple settings simultaneously is in review: https://github.com/cisagov/ScubaGoggles/pull/207
- Creating this issue so that that baseline update to Chat is not blocked by an independent issue; Chat 7.1 and Chat 7.2 can be updated once both PRs are merged to main.

## Implementation notes ##
NA

## Acceptance criteria ##
- Chat 7.1 has a detailed report message
- Chat 7.2 has a detailed report message

**Comment by LaurenBassett** [comment]
Am I missing something or did the updated detail report messages get removed from main after the merge of #176

**Comment by adhilto** [comment]
> Am I missing something or did the updated detail report messages get removed from main after the merge of #176

Most of Chat still has the updated detail report messages in main (just double checked). But Chat.7.1 and Chat.7.2 are new and didn't get the update.
