### ISSUE TITLE
Common Controls 12.1v1 is being duplicated in the report

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGoggles#237]
# 🐛 Summary #

Common Controls 12.1v1 is being duplicated in the report. 
Not sure what the reason for this is. 

## To reproduce ##

Run ScubaGoggles on the main branch with commoncontrols as a baseline selected. 

## Expected behavior ##

Only a single instance of 12.1 is being displayed

## Any helpful log output or screenshots ##
<img width="755" alt="CommonControls" src="https://github.com/cisagov/ScubaGoggles/assets/105074908/88efa961-5b6c-4642-89ed-743a69903b27">

**Comment by adhilto** [comment]
This is actually by-design, though I'm sure there's a better way we could have done it.

![image](https://github.com/cisagov/ScubaGoggles/assets/106177711/d118f4f8-8d06-4f36-a906-4afec601c7a8)

The first row in the report corresponds to the arrow at the top, i.e., "Currently unable to check that Google takeout is disabled for services without..", which for some reason doesn't produce a log event.

The second row corresponds to "apps with individual admin control[s]," which do produce a logs event.

**Comment by adhilto** [comment]
EDIT: I just checked. While what I said was once upon a time true, the top part _does_ produce a log event now. So I would recommend implementing a check for that and combining the output of those two rows into a single row.

![image](https://github.com/cisagov/ScubaGoggles/assets/106177711/93f697b0-8460-4f03-a356-043349d024b9)
