### ISSUE TITLE
GWS.COMMONCONTROLS.14.1v0.1 implementation steps incomplete

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGoggles#240]
The baseline requirement:
![image](https://github.com/cisagov/ScubaGoggles/assets/106177711/bf22dd17-5448-46bf-8d09-f7f83f1a9c9d)

What the implementation steps say to do:
![image](https://github.com/cisagov/ScubaGoggles/assets/106177711/7863f951-31b0-454a-8df6-2b1675b19e9f)

This will send logs to GCP. But the requirement is to send the logs to "the agency's centralized SEIM," which seems like would require an additional step, depending on what the agency is using as their SEIM.

**Comment by jkaufman-mitre** [comment]
Will assess with the team and make needed changes.

**Comment by jkaufman-mitre** [comment]
Will discuss with @tmcomeau to determined what action should be taken.

**Comment by jkaufman-mitre** [comment]
After discussing this issue with @tmcomeau, @lrsmitre, @prodjom, and @mdueltgen we believe changes need to be made. We propose the following options:

Option 1: Leave the policy as is and add an implementation step saying to follow the steps in the GCP link I found for sending logs to a SIEM.

Option 2: Change the policy to make the requirement to have the logs sent to GCP and in the not say that the policy is to facilitate the sending of logs to SIEM.

@adhilto and @buidav Which option do you think would be the best as we cannot include specific implementation on how to connect to a SIEM as it could be different for each agency.

**Comment by jkaufman-mitre** [comment]
@buidav Ok, thank you! I will use the instructions you provided.
