### ISSUE TITLE
Consider increasing super admin limit

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGoggles#252]
Per https://github.com/cisagov/ScubaGoggles/pull/242#discussion_r1548726073, "Note that there is an equivalent policy in the Microsoft 365 AAD/Entra ID SCuBA Baseline. The maximum was bumped up to 8 users from 4 because of pilot feedback from over there."

**Comment by jkaufman-mitre** [comment]
I will confirm with team, but since it was changed on Microsoft I see them changing here.

**Comment by jkaufman-mitre** [comment]
Pull request created.

**Comment by jkaufman-mitre** [comment]
@adhilto We are taking the recommendation. The PR was already created. This change is being made because of the feedback from Microsoft pilots, to be consistent with the Microsoft policy, and based on feedback from Google pilots.

**Comment by jkaufman-mitre** [comment]
Going to create another PR with these changes due to the amount the changes that have occurred.
