### ISSUE TITLE
Evaluate the 12-character password requirement

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGoggles#253]
With regard to GWS.COMMONCONTROLS.5.2, what is the motivation for the number 12? More is obviously stronger, but NIST guidance specifies 8 characters (https://pages.nist.gov/800-63-3/sp800-63b.html). Is there a specific reason we're deviating from NIST guidance (beyond "more is better")?

**Comment by jkaufman-mitre** [comment]
@adhilto I will talk to our team as I was not around when that policy was initially created.

**Comment by jkaufman-mitre** [comment]
@adhilto I am wondering if they got that number from this Google article:
- [Create a strong password & a more secure account](https://support.google.com/accounts/answer/32040?hl=en#zippy=%2Cmake-your-password-longer-more-memorable)

**Comment by jkaufman-mitre** [comment]
@adhilto After discussion internally, we are going to keep it at minimum as 12 and cited the google recommendation from the article above. Even though NIST says 8 characters, Google says 12 and DISA standards is 15.

**Comment by mdueltgen** [comment]
Password length changes have been made in #460
