### ISSUE TITLE
Gmail 16.1 - Security Sandbox setting unavailable in admin console

### ISSUE THREAD

**Issue by snarve** [cisagov/ScubaGoggles#268]
# 🐛 Summary #

Gmail baseline policy 16.1 : Security sandbox SHOULD be enabled to provide additional protections for their email messages, the implementation steps are not available in the admin console.

**Steps**: 

1. Follow the implementation steps from the Gmail baseline policy 16.1
2. In the admin console go to Gmail -> Spam Phishing and Malware
3. 'Security Sandbox' setting is not avaialable

**Comment by jkaufman-mitre** [comment]
@snarve The setting is there. It is exactly where the implementation steps says it is. Please refer to the photo below.

![Screenshot 2024-04-12 at 6 34 34 AM](https://github.com/cisagov/ScubaGoggles/assets/135844572/8f0a4d16-6594-4be0-ab55-2386860120fa)

**Comment by jkaufman-mitre** [comment]
Based on the fact that the setting is present, I recommend closing this issue. @snarve

**Comment by snarve** [comment]
Looks like it is due to some limitations in the tenant. I am using the sandia tenant and do not see it there.

![image](https://github.com/cisagov/ScubaGoggles/assets/108771509/edc70822-556f-4883-bb06-207f46ffe24d)

Agreed, no changes are required, but will follow up on this to figure out why it doesn't show in the other tenant.

**Comment by snarve** [comment]
Closing this issue as test tenant does not have the required license to view certain settings
