### ISSUE TITLE
GWS DriveDocs 1.6 v0.1 Policy Changes

### ISSUE THREAD

**Issue by mdueltgen** [cisagov/ScubaGoggles#289]
After 0.2 Release

Policy re-evaluation might be needed because setting is enabled always, just need to make sure it's not set to public.

Might need to re-adjust rationale as well.

**Comment by mdueltgen** [comment]
Branch was created and changes were made. Waiting until the release of version 0.2 of the baselines before creating PR. Changes made in "drive-docs-changes-post-0.2"

**Comment by jkaufman-mitre** [comment]
PR has been created. Please refer to PR 311. Moving to in review.
