### ISSUE TITLE
possible issue with documentation

### ISSUE THREAD

**Issue by rbailey64** [cisagov/ScubaGoggles#291]
Under the "Create an OAuth credential" documentation, we are asked to move the resulting "client_secret*.json" file into the root directory folder of the repo and rename it "credentials.json"

Then under the "Using a Service Account" section, we are asked to move the resulting "<service account>*.json" into the root directory folder of the repo and also rename it "credentials.json"

You can't have two files in the same root directory with the same name. I guess I am missing something?

**Comment by jkaufman-mitre** [comment]
@LaurenBassett and @adhilto Do you know how to fix this issue?
