### ISSUE TITLE
Gmail policy 9, policy statement and implementation steps are not in sync

### ISSUE THREAD

**Issue by snarve** [cisagov/ScubaGoggles#298]
# 🐛 Summary #

Gmail policy 9, policy statement and implementation steps are inconsistent

![image](https://github.com/cisagov/ScubaGoggles/assets/108771509/1df91120-ea59-463c-949a-ef467fceb457)

![image](https://github.com/cisagov/ScubaGoggles/assets/108771509/1ada57d2-ce60-48ee-ae7f-f0b2573023b1)

In the implementation steps, policy statement from 9.1 is split across implementation steps in 9.1 and 9.2

**Comment by snarve** [comment]
Linked to #288 

Update implementation steps as part of #288

**Comment by jkaufman-mitre** [comment]
@snarve I will work on fixing this.

**Comment by snarve** [comment]
> @snarve I will work on fixing this.

Thank you

**Comment by jkaufman-mitre** [comment]
Remove Policy Gmail 9.2 and move it to 9.1 as a note.

**Comment by jkaufman-mitre** [comment]
Handled this change under the new PR 310.
