### ISSUE TITLE
Split up the main README

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGoggles#306]
# 💡 Summary #
Split up the main README into separate files.

## Motivation and context ##
The README is growing large and unwieldy. Splitting it into smaller files will improve readability and maintainability.

## Implementation notes ##
See ScubaGear's README for reference: https://github.com/cisagov/ScubaGear/tree/main

## Acceptance criteria ##
- [ ] The README has been split into different files, using a structure similar to ScubaGear's documentation.

**Comment by LaurenBassett** [comment]
Linking #283 since it is a readme related issue
