### ISSUE TITLE
Clarify GWS.DRIVEDOCS.3.1v0.2

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGoggles#313]
This policy currently reads as: "Agencies SHALL enable security updates for Drive files." This wording make it sound like [GWS.GMAIL.5.4v0.2](https://github.com/cisagov/ScubaGoggles/blob/main/baselines/Gmail%20Minimum%20Viable%20Secure%20Configuration%20Baseline%20v0.2.md#gwsgmail54v02), "apply future recommend settings." The rationale supports this interpretation: "Google may add new security features over time. Allowing security updates helps ensure that your files are protected with the latest features Google makes available."

However, digging deeper, it turns out the setting in question is about applying _a specific security update_ that has already been published, not about applying new updates as they come. See [Link-sharing security update to Drive](https://apps.google.com/supportwidget/articlehome?article_url=https%3A%2F%2Fsupport.google.com%2Fa%2Fanswer%2F10685032%3Fvisit_id%3D638533824698144528-3160863719&assistant_event=welcome&assistant_id=mega-bot-shared-drive&product_context=10685032&product_name=UnuFlow&trigger_context=a) for more information.

I recommend the following:
- Clarify the policy wording. Maybe "Agencies SHALL enable the security update for Drive files."
- Clarify the rationale.
- Swap out the link that's currently in the resources section for the one I pasted above. The current one doesn't work ("Sorry, this page can't be found.")

**Comment by jkaufman-mitre** [comment]
We will work on making the changes suggested above.
