### ISSUE TITLE
Moving COMMONCONTROLS.11.2v0.2 into Policy Group 10

### ISSUE THREAD

**Issue by jkaufman-mitre** [cisagov/ScubaGoggles#318]
Common Controls Policy 11.2 will be moved into Policy Group 10 since 11.2 does not related to Google Marketplace, but rather API access.

**Comment by snarve** [comment]
Will be handled separately (not covered in PR https://github.com/cisagov/ScubaGoggles/pull/315) post Coast release.

**Comment by snarve** [comment]
@mdueltgen moved this to In-progress for tracking purposes.

**Comment by jkaufman-mitre** [comment]
@mdueltgen Do we know if this was ever handled?
