### ISSUE TITLE
Determine the minimum supported Python version

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGoggles#321]
# 🐛 Summary #
Currently we're listing the minimum supported Python version as 3.7.16. However, during pilot testing we've found that that version is too old and is incompatible with the libraries ScubaGoggles uses.

Additionally, we need to take another look at the Python module versions. The version of the requests module we're currently requiring has been [yanked](https://pypi.org/project/requests/#history) and needs to be updated as well.

## To reproduce ##
Try to run ScubaGoggles on version 3.7.16.

## Expected behavior ##
ScubaGoggles to list the actual minimum supported Python version.

**Comment by aormu** [comment]
The minimum supported Python is 3.8.4.  Python 3.7.16 is sunset.

**Comment by mitchelbaker-cisa** [comment]
Quick note related to this issue and #326. Numpy v1.24.4 is the highest supported version for Python v3.8.x. Numpy v1.26.4 seems to only be supported on Python v3.9+.

**Comment by aormu** [comment]
Test python version 3.9 locally per discussion. The minimum version pandas version supported by python 3.9 is 1.5.0 and numpy version 1.26.0. Pandas 2.x is not compatible with Python 3.9.

**Comment by aormu** [comment]
Agree. I  tested with python 3.10. Minimum support pandas version is 2.0.0.

**Comment by snarve** [comment]
update readme.txt, requirements file and setup.py

**Comment by adhilto** [comment]
> Per discussion, python 3.9 is the minimum version ScubaGoggle will support. Tested python version 3.9 locally. The minimum version pandas version supported by python 3.9 is 1.5.0 and numpy version 1.26.0. Pandas 2.x is not compatible with Python 3.9.

@aormu Where did you see that Pandas 2.x isn't compatible with 3.9? The release notes for Pandas 2.2.2 says that it is.
https://github.com/pandas-dev/pandas/releases
