### ISSUE TITLE
DefaultSafe variable is incorrect in many cases

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGoggles#328]
# 🐛 Summary #
The `DefaultSafe` is a boolean variable in the Rego, intended to indicate whether the default value in the GWS admin center complies with the baseline. However, there are many cases where the `DefaultSafe` listed in the Rego is incorrect.

Cases where `DefaultSafe` should be set to true:
- GWS.GROUPS.1.1, GWS.GROUPS.2.1, GWS.GROUPS.3.1, GWS.GROUPS.6.1
- GWS.MEET.4.1, GWS.MEET.5.1
- GWS.DRIVEDOCS.1.3, GWS.DRIVEDOCS.1.8, GWS.DRIVEDOCS.2.3, GWS.DRIVEDOCS.2.4, GWS.DRIVEDOCS.3.1
- GWS.CLASSROOM.1.1, GWS.CLASSROOM.1.2
- GWS.CHAT.1.1, GWS.CHAT.3.1
- GWS.CALENDAR.1.1, GWS.CALENDAR.2.1, GWS.CALENDAR.3.1, GWS.CALENDAR.4.1
- GWS.GMAIL.5.1, GWS.GMAIL.5.2, GWS.GMAIL.5.4, GWS.GMAIL.6.1, GWS.GMAIL.6.2, GWS.GMAIL.6.3, GWS.GMAIL.6.4, GWS.GMAIL.7.1, GWS.GMAIL.7.2, GWS.GMAIL.7.3, GWS.GMAIL.7.7, GWS.GMAIL.8.1, GWS.GMAIL.12.1, GWS.GMAIL.13.1, GWS.GMAIL.14.1, GWS.GMAIL.15.1
- GWS.COMMONCONTROLS.5.1, GWS.COMMONCONTROLS.5.4, GWS.COMMONCONTROLS.5.5, GWS.COMMONCONTROLS.10.3, GWS.COMMONCONTROLS.11.2, GWS.COMMONCONTROLS.15.2

Cases where `DefaultSafe` should be set to false:
- GWS.CLASSROOM.4.1
- GWS.COMMONCONTROLS.12.1

## To reproduce ##
While inside a brand new, default state GWS environment, check the default values.

## Expected behavior ##
The `DefaultState` coded in the Rego to be correct in all cases.

**Comment by snarve** [comment]
@aormu can you create a PR for this issue
