### ISSUE TITLE
Create temporary release branch for baseline updates

### ISSUE THREAD

**Issue by snarve** [cisagov/ScubaGoggles#364]
# 💡 Summary #

Create temporary release branch for baseline updates during baseline review period

## Motivation and context ##

- While baselines are in review, the baseline updates can continue on this temporary release branch in preparation for the next release cycle
- Only baseline updates will be made in this branch and blocked issues will be created for any corresponding code updates to be handled post the current release

## Implementation notes ##

- Create a temporary branch for baseline updates once the baseline version numbers are updated in main 

## Acceptance criteria ##

- [x] Temporary branch is created for baseline updates 
- [ ] Instructions to update on this branch are documented

**Comment by adhilto** [comment]
Branch created and branch protection rules applied: https://github.com/cisagov/ScubaGoggles/tree/driftwood
