### ISSUE TITLE
Functional Testing for Gmail 

### ISSUE THREAD

**Issue by snarve** [cisagov/ScubaGoggles#385]
Key points:

- [x] Test all the baseline policies
- [x] Test different use cases and edge cases
- [x] For each policy verify if the output as expected when the tests pass/fail
- [x] For policies with multiple settings check that only the expected sub-policy will pass/fail and the other
- [x] dependent/independent policies are unaffected
- [x] Perform tests to verify multiple OU and OU inheritance settings wherever applicable
- [x] Perform tests to verify Group settings wherever applicable
- [x] Report and file bugs for any issues found

**Comment by LaurenBassett** [comment]
Is anyone else having issues running gmail? 

I get the following error: 


```
Traceback (most recent call last):                                                                                    
  File "/Projects/CISA_SCuBA/ScubaGoggles/.venv/bin/scubagoggles", line 8, in <module>
    sys.exit(dive())
             ^^^^^^
  File "Projects/CISA_SCuBA/ScubaGoggles/.venv/lib/python3.12/site-packages/scubagoggles/main.py", line 143, in dive
    Orchestrator(args).start_automation()
  File "Projects/CISA_SCuBA/ScubaGoggles/.venv/lib/python3.12/site-packages/scubagoggles/orchestrator.py", line 420, in start_automation
    self._run_reporter()
  File "/Projects/CISA_SCuBA/ScubaGoggles/.venv/lib/python3.12/site-packages/scubagoggles/orchestrator.py", line 287, in _run_reporter
    baseline_policies[product],
    ~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'gmail'

```

**Comment by LaurenBassett** [comment]
GWS.GMAIL.1.1v0.3
Tested: 
- OU Fail 
- OU and Tenant Fail 
- OU Change to Pass w/o inherit 
- OU change w/inherit 
- Tenant Pass 
-

**Comment by LaurenBassett** [comment]
2.1  Might take 48 Hours 
-Stopped authentication
- No granular settings for groups or admins 

**For now, no change in status.**

**Comment by LaurenBassett** [comment]
3.1 - 
Looks like it is dependent on 2.1? Might need some assistance in the functional testing here.

**Comment by LaurenBassett** [comment]
4.1-4.4 - Again some DMARC issues making it less straightforward  to functional test.

**Comment by LaurenBassett** [comment]
Gmail 1 - Good 
Gmail 2-4 Circle Backl
Gmail 5 - Good

**Comment by LaurenBassett** [comment]
I'm going to go ahead and close this issue, since I completed the functional testing. However, I identified one bug. See issue #463 for more information.
