### ISSUE TITLE
GWS.GMAIL.5.5 has the wrong criticality in the code

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGoggles#396]
# 🐛 Summary #
GWS.GMAIL.5.5 is a "SHALL" control, but the criticality listed in the Rego is "Should."

## To reproduce ##
1. Change one of the attachment settings to "keep in inbox"
2. Run ScubaGoggles. Note that 5.5 shows as a "Warning" not a "Failure"

## Expected behavior ##
5.5 non-compliance to be reported as a failure.

## Any helpful log output or screenshots ##
![image](https://github.com/user-attachments/assets/b69ff7a6-8594-499a-a5bb-1e6ab5b6c012)

**Comment by snarve** [comment]
Covered in PR #394
