### ISSUE TITLE
GWS.GMAIL.7.6 has the wrong criticality in the code

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGoggles#397]
# 🐛 Summary #
GWS.GMAIL.7.6 is a "SHALL" control, but the criticality listed in the Rego is "Should."

## To reproduce ##
1. Change one of the spoofing settings to "keep in inbox"
2. Run ScubaGoggles. Note that 7.6 shows as a "Warning" not a "Failure"

## Expected behavior ##
5.5 non-compliance to be reported as a failure.

## Any helpful log output or screenshots ##
![image](https://github.com/user-attachments/assets/3dc8ba19-e1a4-4757-b3cd-8dd4ea45bb87)

**Comment by snarve** [comment]
Covered in PR #394
