### ISSUE TITLE
Correct pylint Errors

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGoggles#430]
# 💡 Summary #
Correct the following lint errors:
![image](https://github.com/user-attachments/assets/a193d28e-4fc0-4208-a38d-952f482d2695)

## Motivation and context ##
pylint version 3.3.0, which was just released (Sep 20, 2024), apparently added checks that our code does not currently pass. As a temporary measure I've pinned pylint in the workflow to version 3.2.7. We should update the workflow to the latest version and either refactor our code to pass the checks or configure more exceptions in the workflow.

## Implementation notes ##
pylint version pinned here: https://github.com/cisagov/ScubaGoggles/blob/c8d0c9357792f569fb18bcae4cb56f99843af321/.github/workflows/pylint.yml#L34

## Acceptance criteria ##
- [ ] Workflow uses the latest version of pylint
- [ ] Workflow passes

**Comment by snarve** [comment]
new updates may have resolved this, confirm?

**Comment by adhilto** [comment]
> new updates may have resolved this, confirm?

Keep open for now, the PR linked to this issue will resolve it, it should close automatically once the PR is merged.
