### ISSUE TITLE
Weird Bug When Running ScubaGoggles

### ISSUE THREAD

**Issue by LaurenBassett** [cisagov/ScubaGoggles#447]
# 🐛 Summary #

What's wrong? Please be specific.

-MacOS, Apple Chip 

## To reproduce ##

When running ScubaGoggles in the virtual environment set up, if I run the code with the `scubagoggles gws -b`  command, it fails with a key error in the orchestrator. 

```
Traceback (most recent call last):                      
  File ".../ScubaGoggles/.venv/bin/scubagoggles", line 8, in <module>
    sys.exit(dive())
             ^^^^^^
  File ".../ScubaGoggles/.venv/lib/python3.12/site-packages/scubagoggles/main.py", line 143, in dive
    Orchestrator(args).start_automation()
  File ".../ScubaGoggles/.venv/lib/python3.12/site-packages/scubagoggles/orchestrator.py", line 420, in start_automation
    self._run_reporter()
  File ".../ScubaGoggles/.venv/lib/python3.12/site-packages/scubagoggles/orchestrator.py", line 287, in _run_reporter
    baseline_policies[product],
    ~~~~~~~~~~~~~~~
KeyError: 'gmail'
``` 

However, if I run the code with `python3 scuba.py gws -b gmail` it works just fine. 

I'm not sure if this is a me problem, a Mac problem, or a code problem, but I figured I would document it.

**Comment by adhilto** [comment]
I've seen something like this before. Take a look at https://github.com/cisagov/ScubaGoggles/blob/424-add-instructions-for-upgrading-try-again/docs/upgrading/Upgrading.md#upgrading-scubagoggles (new file, still in review). Specifically this bit: "If instead you cloned the ScubaGoggles repo and wish to run ScubaGoggles on the latest code from main (only recommended for development purposes), be sure to run `python -m pip install .` inside the ScubaGoggles directory after pulling the latest code." That should hopefully fix the issue. Let me know if it doesn't.

**Comment by LaurenBassett** [comment]
> I've seen something like this before. Take a look at https://github.com/cisagov/ScubaGoggles/blob/424-add-instructions-for-upgrading-try-again/docs/upgrading/Upgrading.md#upgrading-scubagoggles (new file, still in review). Specifically this bit: "If instead you cloned the ScubaGoggles repo and wish to run ScubaGoggles on the latest code from main (only recommended for development purposes), be sure to run `python -m pip install .` inside the ScubaGoggles directory after pulling the latest code." That should hopefully fix the issue. Let me know if it doesn't.



Yes that works. Guess it makes sense why I missed it. Thanks!
