### ISSUE TITLE
GWS.COMMONCONTROLS.11.2v0.3 does not detect setting inheritance

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGoggles#465]
# 🐛 Summary #
GWS.COMMONCONTROLS.11.2v0.3 does not detect setting inheritance (for both OUs and groups)

## To reproduce ##
1. Follow https://github.com/cisagov/ScubaGoggles/blob/main/baselines/commoncontrols.md#gwscommoncontrols112v03-instructions. Ensure there is an event for the top-level OU
2. Make a child OU or a group non-compliant.
3. Click "Inherit" (or "Unset" for a group).
4. Run ScubaGoggles. The child OU or group will still show as non-compliant.

## Expected behavior ##
The child OU / group to show as compliant if it inherits from its parent.

## Any helpful log output or screenshots ##
N/A

**Comment by snarve** [comment]
This is moved to 10.5 (confirm) #487 
 
#318

**Comment by adhilto** [comment]
> This is moved to 10.5
> 
> Related issue and PR: [#487](https://github.com/cisagov/ScubaGoggles/pull/487)
> 
> [#318](https://github.com/cisagov/ScubaGoggles/issues/318)
> 
> Can this be closed?

Moving to the control to a different policy group wouldn't resolve the underlying bug. Leave open until we test and confirm the issue is resolved. It's good to note the new number though, your comment should help whoever takes this issue.

**Comment by adhilto** [comment]
This setting can be queried using the policy API, so this issue will be fixed in https://github.com/cisagov/ScubaGoggles/pull/499.
