### ISSUE TITLE
Clarify rules instructions

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGoggles#467]
# 💡 Summary #
One of the instructions steps says: "From the Actions page, you can change the severity for the alert to High, Medium, or Low, send an alert to the alert center if the rule's conditions are met, set up admin email notifications, and specify recipients for those notifications."

As a user, I want to know what I _need_ to do, rather than what I _can_ do. I can see for myself what I can do just by looking around. What isn't immediately clear is what needs to be done to meet the baseline requirement.

Also, there's a step missing between "Select the rule by clicking the table row for the rule" and "Click Next: View Conditions." You need click "Edit rule" first. Alternatively, you can skip straight to the actions page by just clicking the "Actions" box, which would cut out two steps.

## Implementation notes ##
The required action is:
- Enable admin center alerts, if that option is available
- If admin center alerts are not an available, enable email notifications.

Notably, not all rules support admin center alerts (e.g., "TLS Failure"), which is something we should note in the baseline.

## Acceptance criteria ##
- [ ] Instructions have been clarified with required actions
- [ ] Instructions have been adjusted to cover the missing step

**Comment by mdueltgen** [comment]
Just wanted to confirm this is for the implementation steps of Common Controls 13.1?
