### ISSUE TITLE
Turn on snippets for additional context surrounding data loss prevention rule violations

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#53]
Admins can now view ‚ÄúSensitive Content Snippets‚Äù for data loss prevention (DLP) rules. This applies to DLP events for Drive, Chat, and Chrome. When turned on, snippets will log the matched content that triggered a DLP violation in the security investigation tool. Admins can use the information captured in the snippet to better identify actual security risks, determine whether a false positive was returned, and decide on an appropriate course of action. 

Publish Date: Wednesday, December 6, 2023
[Update Blog Link](http://workspaceupdates.googleblog.com/2023/12/data-loss-prevention-rule-violation-snippets.html)

**Comment by jkaufman-mitre** [comment]
This is being deferred to the hardening guide. No changes required to baseline.
