### ISSUE TITLE
Set client-side encryption as the default mode for new emails, events, and files

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#54]
Publish Date: Tuesday, December 5, 2023
[Update Blog Link](http://workspaceupdates.googleblog.com/2023/12/turn-client-side-encryption-on-by-default.html)

**Comment by tmcomeau** [comment]
@jkaufman-mitre defer to HG as discussed since this deals with client-side encryption.

**Comment by jkaufman-mitre** [comment]
This update is being deferred to the hardening guide. No changes needed.
