### ISSUE TITLE
Admins in Google Vault can now export hyperlinked Google Drive content from Gmail messages

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#55]
Admins can export Drive files hyperlinked in Gmail messages directly in Google Vault.

Publish Date: Tuesday, December 5, 2023
[Update Blog Link](http://workspaceupdates.googleblog.com/2023/12/google-vault-export-hyperlinked-drive-content-from-gmail-messages.html)

**Comment by jkaufman-mitre** [comment]
After reviewing this update again, it does not have any admin controls for this update. Closing this update out.
