### ISSUE TITLE
New Update for Classroom SIS Connection

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#58]
Educators can now easily import students from their student information system (SIS) to Google Classroom using OneRoster. This integration saves educators time and helps make class setup much quicker.
[Update Blog Link](https://workspaceupdates.googleblog.com/2023/11/google-classroom-now-supports-roster-import.html)

**Comment by jkaufman-mitre** [comment]
Based on our review of this update, there is no security implication for this update as this feature only allows the import of data from an SIS into Google Classroom. Being that this would be an critical function for schools that use an SIS, it would be too prohibitive to have a policy not allowing this.
