### ISSUE TITLE
GWS.GMAIL.12.1 has no security benefits and is a counter recommendation

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#60]
GWS.12.1 recommends organizations create an allowlist/whitelist just to avoid broken links. 

Not sure what the security benefits of this policy are.
This policy is recommending an image domain allowlist which is counter to policies we've had in the past which is to recommend against allowlists. 
If this setting is just for fixing broken image links and does not provide a security benefit, I would recommend removal.  
¬†
Even the Google documentation for this policy recommends users tread carefully when implementing this setting. 

#### GWS.GMAIL.12.1v0.1
Image URL proxy whitelists SHOULD be enabled to avoid broken links to images that are dependent on internal IP addresses within an organization's domain.

**Comment by adhilto** [comment]
Duplicated by #137.
