### ISSUE TITLE
GWS.GMAIL.15, GWS.GMAIL.18, GWS.GMAIL.19; Contradictions and Duplications 

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#61]
- GMAIL.15.1 contradicts 18.1 and 18.2. 
- GMAIL.15.2 overlaps and is redundant with 19.1 which is also redundant with 19.2.

Note that addressing these issues require large changes. So, pushing this issue to the backlog for now.

Policy 15.1 says to not use email allowlists, yet 18.1 and 18.2 says that we should? Also 18.2 duplicative of 18.1 except for the caveat. 
```
#### GWS.GMAIL.15.1v0.1
An email allowlist SHOULD not be implemented.

#### GWS.GMAIL.18.1v0.1
An Approved Senders List SHOULD be configured to keep legitimate emails out of the spam folder.

#### GWS.GMAIL.18.2v0.1
An allowed senders list MAY be added but SHOULD NOT add allowed domains.
```

Policies 15.2, and 19.1, and 19.2 all are saying the same thing. We should choose one then delete the others. 

```
#### GWS.GMAIL.15.2v0.1
A connection filter policy to create a Blocked Senders list MAY be implemented.

#### GWS.GMAIL.19.1v0.1
A blocked senders list SHOULD be configured to prevent emails from known malicious sources.

#### GWS.GMAIL.19.2v0.1
Blocked senders or domains MAY be added to the blocked senders list.
```

**Comment by adhilto** [comment]
Duplicated by #137.
