### ISSUE TITLE
Combine Chat 4.1 and 4.2

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#63]
Combined CHAT.4.1v0.1 and CHAT.4.2v0.1 into one policy. Waiting drift rules update.

**Comment by snarve** [comment]
![image](https://github.com/cisagov/ScubaGoggles/assets/108771509/1dfd4864-0bee-4c56-b989-f6037f03b63e)

@jkaufman-mitre the above two policies can be combined into a single policy.

@LaurenBassett please confirm if we can combine these into a single policy as they both are listing the same policy definition (Chat 4.1 and 4.2)

**Comment by adhilto** [comment]
Hi @snarve,

I actually still think chat 4.1 and 4.2 should be combined into just "External Chat messaging SHALL be restricted to allowlisted domains only."

My reasoning:
- The controls are duplicative (when considering just the policy language). Both effectively just say "External Chat messaging SHALL be restricted to allowlisted domains only," though Chat 4.2 says it in a confusing way.
- The implementation for 4.1 does not match the policy for 4.1. The policy says, "External Chat messaging SHALL be restricted to allowlisted domains only," while the implementation effectively says, "External Chat messaging SHALL be enabled." Disabling external chat completely would still meet the policy requirement but would go against the implementation. An agency shouldn't _have_ to enable external chat just to be compliant. If we combine the two controls into one, we could provide instructions for either disabling it completely or using an allowlist.

**Comment by snarve** [comment]
> Hi @snarve,
> 
> I actually still think chat 4.1 and 4.2 should be combined into just "External Chat messaging SHALL be restricted to allowlisted domains only."
> 
> My reasoning:
> 
> * The controls are duplicative (when considering just the policy language). Both effectively just say "External Chat messaging SHALL be restricted to allowlisted domains only," though Chat 4.2 says it in a confusing way.
> * The implementation for 4.1 does not match the policy for 4.1. The policy says, "External Chat messaging SHALL be restricted to allowlisted domains only," while the implementation effectively says, "External Chat messaging SHALL be enabled." Disabling external chat completely would still meet the policy requirement but would go against the implementation. An agency shouldn't _have_ to enable external chat just to be compliant. If we combine the two controls into one, we could provide instructions for either disabling it completely or using an allowlist.
> 
> Even though two distinct settings are involved, Rego is able to handle cases like this if we were to combine them.

agreed, this can be implemented similar to Drive 6.1, so restrict External Chat Sharing to allowlisted domain only.

**Comment by snarve** [comment]
created a branch and updated the code for now.

since this requires baseline policy update, after a follow up discussion and update to the policy the code changes can be integrated.

**Comment by jkaufman-mitre** [comment]
@snarve Where is the branch for these changes as there is no PR for this.

**Comment by snarve** [comment]
> @snarve Where is the branch for these changes as there is no PR for this.

Branch: [63-combine-chat-41-and-42](https://github.com/cisagov/ScubaGoggles/tree/63-combine-chat-41-and-42)

**Comment by snarve** [comment]
@jkaufman-mitre is the SCB update on this completed

**Comment by jkaufman-mitre** [comment]
@snarve No not yet.

**Comment by snarve** [comment]
Thank you @jkaufman-mitre. Will test and make any pending code changes.
