### ISSUE TITLE
Chat 4.2 SCB Update

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#65]
Dev team found an issue with the baseline for GWS.CHAT.4.2v0.1.

You are the TCO, however, wait until I get more details on the change from Lauren before making any changes. I will let you know once I know more.

**Comment by adhilto** [comment]
@jkaufman-mitre see https://github.com/cisagov/ScubaGoggles/issues/63#issuecomment-1927883611 for more details.

**Comment by LaurenBassett** [comment]
Closing because it is duplicate of #63
