### ISSUE TITLE
Functional Testing for Calendar

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#72]
Key points:

- [x] Test all the baseline policies
- [x] Test different use cases and edge cases
- [ ] For each policy verify if the output as expected when the tests pass/fail
- [x] For policies with multiple settings check that only the expected sub-policy will pass/fail and the other
- [x] dependent/independent policies are unaffected
- [x] Perform tests to verify multiple OU and OU inheritance settings wherever applicable
- [ ] Perform tests to verify Group settings wherever applicable
- [x] Report and file bugs for any issues found

**Comment by adhilto** [comment]
Testing complete. One bug found, logged as https://github.com/cisagov/ScubaGoggles/issues/395.
