### ISSUE TITLE
Drive 1.1 policy statement is contradicting

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#73]
1.2 through 1.4 refer to settings when 1.1 is set to Allow Listed Domains (second radio button option)
However, 1.1 talks about setting the option as 'ON' or 'OFF' and not the 'Allow Listed Domains'

**Comment by LaurenBassett** [comment]
I believe this issue can be closed, as the contradiction has been addressed. 

> If this policy is enforced, then follow Policy 1.2
> If this policy is not enforced, then follow Policies 1.3 and 1.4
