### ISSUE TITLE
Gmail 7.6 logic is incomplete

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#75]
Gmail 7.6: Emails flagged by the above spoofing and authentication controls SHALL NOT be kept in inbox.

Rego logic is incomplete. When enabling settings 7.1 - 7.5. There is the default option and the option to add to spam or quarantine.
Issue is when you leave the setting the the default `show warning` the log event will not indicate if the setting is set to `show warning` or `quarantine`

The rego currently only can check if the setting is enabled not what value it is changed to. After the first log event however, then the setting shows up for any additional change events. Tricky situation. Will need to find a way to handle this.

**Comment by snarve** [comment]
Handled in #394
