### ISSUE TITLE
Functional Testing for Chat

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#78]
Key points:

- [x]  Test all the baseline policies
- [x]  Test different use cases and edge cases
- [x]  For each policy verify if the output as expected when the tests pass/fail
- [x]  For policies with multiple settings check that only the expected sub-policy will pass/fail and the other dependent/independent policies are unaffected
- [x] Perform tests to verify multiple OU and OU inheritance settings wherever applicable
- [x] Perform tests to verify Group settings wherever applicable
- [x] Report and file issues for any problems found

**Comment by adhilto** [comment]
Testing complete. No issues found.
