### ISSUE TITLE
Implement auth by service account

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#82]
We're currently only using authentication via [OAuth](https://developers.google.com/identity/protocols/oauth2) which requires an admin in the flow to periodically consent.

This issue is to implement authentication via [Service Account](https://cloud.google.com/iam/docs/service-account-overview) for MTA purposes.

**Comment by jacdavi** [comment]
It looks like I have this working. Don't have a PR yet, but wanted to capture the changes:

1. In `auth.py` add support for loading credentials for a service account. That looks something like
```python
creds = SvcCredentials.from_service_account_file(cred_path).with_scopes(SCOPES).with_subject(user_email)
```
This requires adding a new parameter for `user_email` which is the email address of a user that has necessary access to the APIs.

2. Add a new paramater for `customer_id`. It should replace instances of `my_customer` in API calls (but can default to that value).

3. The service account will need domain-wide delegation with the API scopes to be able to run. (doesn't need to be assigned an admin role like we thought.)

**Comment by jacdavi** [comment]
> > 3. The service account will need domain-wide delegation with the API scopes to be able to run. (doesn't need to be assigned an admin role like we thought.)
> 
> Any reason domain-wide delegation needs to be enabled for the service account in our use case? Haven't dug into it myself but the documentation emphasizes to use domain-wide delegation only as a last resort.

So in testing I get an error `Access denied. You are not authorized to read activity records.` when I don't have domain-wide delegation, but do have the service account added with an appropriate role. I haven't found documentation from Google yet, but SO answers point to needing domain-wide delegation to access activity records. [answer 1](https://stackoverflow.com/a/69403477) | [answer 2](https://stackoverflow.com/a/52057067]
