### ISSUE TITLE
Find the minimum privileges that need to be assigned to a custom admin role to run the tool

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#83]
The permissions needed to access the API with the scopes that we need are a bit vague. 
[The reports API Google Documentation guide](https://developers.google.com/admin-sdk/reports/v1/guides/prerequisites) says that a `super admin` or a `custom admin` is needed to access the API. 

Lessons learned from M365, members of the public aren't comfortable with running some random tool off the internet as the highest privileged role in their Cloud environment. For GWS, this is the `super admin` role.

There is no specific Google Documentation for assigning the custom admin the minimum permissions we need to access the reports and directory apis:

This issue is to find out and document the minimum privileges that need to be assigned to a `custom admin` to run this tool.
Then test if there are any issues running the tool as an account assigned just that custom admin role.
[How to create a custom admin role](https://apps.google.com/supportwidget/articlehome?article_url=https%3A%2F%2Fsupport.google.com%2Fa%2Fanswer%2F2406043%3Ftopic%3D2785005&assistant_event=welcome&assistant_id=usermasterbot&product_context=2406043&product_name=UnuFlow&trigger_context=a).

See the README for the OAuth scopes we're currently using for Goggles

**Comment by jacdavi** [comment]
Testing with the branch for #152 I was able to get the same output as a super admin using a custom role with the following privileges:

Console
* Reports
* Directory Settings > Settings
API
* Organization Units > Read
* Users > Read
* Groups > Read
* Domain Management

Note that selecting some privileges enables others, so in total this role has 11 console privileges and 5 API privileges.

**Comment by adhilto** [comment]
Issue OBE; with the inclusion of the policy API, ScubaGoggles no longer supports custom roles, super admin is required.

**Comment by za** [comment]
Hi @adhilto thanks for addressing this.
