### ISSUE TITLE
Functional Testing Baseline: CommonControls

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#92]
Key points:

- [ ] Test all the baseline policies
- [ ] Test different use cases and edge cases
- [ ] For each policy verify if the output as expected when the tests pass/fail
- [ ] For policies with multiple settings check that only the expected sub-policy will pass/fail and the other
- [ ] dependent/independent policies are unaffected
- [ ] Perform tests to verify multiple OU and OU inheritance settings wherever applicable
- [ ] Perform tests to verify Group settings wherever applicable
- [ ] Report and file bugs for any issues found

**Comment by adhilto** [comment]
One issue found so far: https://github.com/cisagov/ScubaGoggles/issues/453
